version: 2
before:
  hooks:
    - go mod tidy -v
builds:
  - id: linux_amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -s -w
      - -X github.com/hi2shark/santaizi-dashboard/service/singleton.Version={{ .Env.VERSION_TAG }}
      - -extldflags "-static -fpic"
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
snapshot:
  version_template: "dashboard"
