services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        COUNTRY: CN
    image: santaizi:dev
    container_name: santaizi-dev
    ports:
      - ${SANTAIZI_PORT:-80}:18080
      - 5555:5555
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/santaizi-dashboard
      - ./script/config.yaml:/etc/santaizi/dashboard.yaml:ro
