<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { cleanupOfflineHistory, getSettings, updateSettings } from '@santaizi/api'
import { notifyAPIError } from '@/composables/notify'
import LocationPicker from '@/components/LocationPicker.vue'
const { t,te }=useI18n();const saving=ref(false);const form=reactive<Record<string,unknown>>({site_title:'三太子监控',language:'zh-CN',view_password:'',view_password_configured:false,clear_view_password:false,grpc_host:'',proxy_grpc_port:0,tls:false,nameservers:[],enable_offline_history:true,offline_threshold:30,check_interval:5,merge_gap:0,retention_days:30,notify_offline:true,notify_recovery:true,show_availability_guest:true,connectivity_notification:false,correction_notification:false,collector_offline_notification:true,data_loss_notification:true,primary_color:'#2563eb',footer_text:'',logo_url:'/static/logo.svg',background_url:'',custom_css:'',theme:'server-status',allow_frontend_theme_switch:true,primary_location:''})
async function load(){try{Object.assign(form,await getSettings())}catch(e){notifyAPIError(e,t as never,te)}}
async function save(){saving.value=true;try{Object.assign(form,await updateSettings(form));form.clear_view_password=false;ElMessage.success(t('saveSuccess'))}catch(e){notifyAPIError(e,t as never,te)}finally{saving.value=false}}
async function cleanupHistory(){await ElMessageBox.confirm(t('cleanupHistoryConfirm'),t('confirm'),{type:'warning'});try{const result=await cleanupOfflineHistory();ElMessage.success(t('cleanupHistoryResult',{count:Number(result.deleted||0)}))}catch(e){notifyAPIError(e,t as never,te)}}
onMounted(load)
</script>
<template><div class="page-head"><div><h1>{{t('settings')}}</h1></div><el-button type="primary" :loading="saving" @click="save"><i class="ri-save-line"></i>{{t('save')}}</el-button></div><el-form :model="form" label-position="top" class="settings-stack">
  <section class="surface settings-section"><div class="settings-heading"><i class="ri-window-line"></i><div><h2>{{t('site')}}</h2></div></div><div class="form-grid"><el-form-item :label="t('siteTitle')"><el-input v-model="form.site_title"/></el-form-item><el-form-item :label="t('language')"><el-select v-model="form.language" style="width:100%"><el-option label="简体中文" value="zh-CN"/><el-option label="繁體中文" value="zh-TW"/><el-option label="English" value="en-US"/><el-option label="Español" value="es-ES"/></el-select></el-form-item><el-form-item :label="t('accessPassword')"><el-input v-model="form.view_password" type="password" show-password :placeholder="form.view_password_configured?t('passwordConfigured'):''"><template v-if="form.view_password_configured" #append><el-button @click="form.clear_view_password=true;form.view_password_configured=false"><i class="ri-delete-bin-line"></i>{{t('clearPassword')}}</el-button></template></el-input></el-form-item><el-form-item :label="t('grpcHost')"><el-input v-model="form.grpc_host"/></el-form-item><el-form-item :label="t('grpcProxyPort')"><el-input v-model.number="form.proxy_grpc_port" inputmode="numeric" :placeholder="t('grpcProxyPortPlaceholder')" style="width:100%"/></el-form-item><el-form-item :label="t('grpcTLS')"><el-switch v-model="form.tls"/></el-form-item><el-form-item :label="t('primaryLocation')"><LocationPicker :model-value="String(form.primary_location || '')" @update:model-value="form.primary_location = $event"/></el-form-item><el-form-item class="span-2" :label="t('nameservers')"><el-select v-model="form.nameservers" multiple allow-create filterable style="width:100%"/></el-form-item></div></section>
  <section class="surface settings-section"><div class="settings-heading"><i class="ri-timer-flash-line"></i><div><h2>{{t('offlineSettings')}}</h2></div><el-button plain @click="cleanupHistory"><i class="ri-delete-bin-5-line"></i>{{t('cleanupHistory')}}</el-button></div><div class="form-grid"><el-form-item :label="t('enableOfflineHistory')"><el-switch v-model="form.enable_offline_history"/></el-form-item><el-form-item :label="t('showAvailabilityGuest')"><el-switch v-model="form.show_availability_guest"/></el-form-item><el-form-item :label="t('offlineThreshold')"><el-input v-model.number="form.offline_threshold" inputmode="numeric" style="width:100%"/></el-form-item><el-form-item :label="t('checkInterval')"><el-input v-model.number="form.check_interval" inputmode="numeric" style="width:100%"/></el-form-item><el-form-item :label="t('mergeGap')"><el-input v-model.number="form.merge_gap" inputmode="numeric" style="width:100%"/></el-form-item><el-form-item :label="t('retentionDays')"><el-input v-model.number="form.retention_days" inputmode="numeric" style="width:100%"/></el-form-item><el-form-item :label="t('notifyOffline')"><el-switch v-model="form.notify_offline"/></el-form-item><el-form-item :label="t('notifyRecovery')"><el-switch v-model="form.notify_recovery"/></el-form-item></div></section>
  <section class="surface settings-section"><div class="settings-heading"><i class="ri-notification-badge-line"></i><div><h2>{{t('telemetryNotifications')}}</h2></div></div><div class="setting-switches"><label><span>{{t('connectivityNotification')}}</span><el-switch v-model="form.connectivity_notification"/></label><label><span>{{t('correctionNotification')}}</span><el-switch v-model="form.correction_notification"/></label><label><span>{{t('collectorOfflineNotification')}}</span><el-switch v-model="form.collector_offline_notification"/></label><label><span>{{t('dataLossNotification')}}</span><el-switch v-model="form.data_loss_notification"/></label></div></section>
  <section class="surface settings-section"><div class="settings-heading"><i class="ri-palette-line"></i><div><h2>{{t('appearance')}}</h2></div></div><div class="form-grid"><el-form-item :label="t('publicTheme')"><el-select v-model="form.theme" style="width:100%"><el-option :label="t('themeServerStatus')" value="server-status"/><el-option :label="t('themeNazhua')" value="nazhua"/></el-select></el-form-item><el-form-item :label="t('allowFrontendThemeSwitch')"><el-switch v-model="form.allow_frontend_theme_switch"/></el-form-item><el-form-item :label="t('primaryColor')"><el-color-picker v-model="form.primary_color"/></el-form-item><el-form-item :label="t('footerText')"><el-input v-model="form.footer_text"/></el-form-item><el-form-item :label="t('logoURL')"><el-input v-model="form.logo_url"/></el-form-item><el-form-item :label="t('backgroundURL')"><el-input v-model="form.background_url"/></el-form-item><el-form-item class="span-2" :label="t('customCSS')"><el-input v-model="form.custom_css" type="textarea" :rows="8" class="mono"/><small>{{t('safeCSSRules')}}</small></el-form-item></div></section>
</el-form></template>
