import { computed,reactive,ref } from 'vue';import { getBootstrap,listPublicServers,type ServerRecord,type SiteBootstrap,websocketURL } from '@santaizi/api'
const bootstrap=ref<SiteBootstrap|null>(null),servers=ref<ServerRecord[]>([]),loading=ref(false),connected=ref(false),loadError=ref(false);let socket:WebSocket|undefined,retry=0,timer:number|undefined
function publicNote(value:unknown):Record<string,unknown>{if(value&&typeof value==='object')return value as Record<string,unknown>;if(typeof value==='string'&&value.trim()){try{return JSON.parse(value) as Record<string,unknown>}catch{return {text:value}}}return {}}
export function normalizeServer(raw:Record<string,unknown>):ServerRecord{const value=(raw.data&&typeof raw.data==='object'?raw.data:raw) as Record<string,unknown>;return {id:Number(value.id),name:String(value.name??''),tag:String(value.tag??''),display_index:Number(value.display_index??0),hide_for_guest:Boolean(value.hide_for_guest),enable_ddns:Boolean(value.enable_ddns),public_note:publicNote(value.public_note),host:value.host as Record<string,unknown>,state:value.state as Record<string,unknown>,last_active:String(value.last_active??''),online:Boolean(value.online),telemetry:value.telemetry as ServerRecord['telemetry']}}
async function load(){loading.value=true;try{bootstrap.value=await getBootstrap();const result=await listPublicServers();servers.value=result.data.map(v=>normalizeServer(v as unknown as Record<string,unknown>));loadError.value=false}catch{loadError.value=true}finally{loading.value=false}}
function apply(message:unknown){const value=message as Record<string,unknown>;const list=Array.isArray(value.servers)?value.servers:Array.isArray(message)?message:null;if(list){servers.value=list.map(v=>normalizeServer(v));return}const row=normalizeServer(value);const index=servers.value.findIndex(v=>v.id===row.id);if(index>=0)servers.value[index]={...servers.value[index],...row};else if(row.id)servers.value.push(row)}
function connect(){socket?.close();socket=new WebSocket(websocketURL('/ws/v2/public/runtime'));socket.onopen=()=>{connected.value=true;retry=0};socket.onmessage=e=>{try{apply(JSON.parse(String(e.data)))}catch{}};socket.onclose=()=>{connected.value=false;window.clearTimeout(timer);timer=window.setTimeout(connect,Math.min(30000,1000*2**retry++))};socket.onerror=()=>socket?.close()}
function stop(){window.clearTimeout(timer);socket?.close()}
const groups=computed(()=>{const map=new Map<string,ServerRecord[]>();for(const server of servers.value){const name=server.tag||'default';map.set(name,[...(map.get(name)||[]),server])}return [...map].map(([name,items])=>({name,items}))})
const statusStore=reactive({bootstrap,servers,groups,loading,connected,loadError,load,connect,stop})
export function useStatusStore(){return statusStore}
