// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/santaizi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SantaiziService_ReportSystemState_FullMethodName = "/proto.SantaiziService/ReportSystemState"
	SantaiziService_ReportSystemInfo_FullMethodName  = "/proto.SantaiziService/ReportSystemInfo"
	SantaiziService_ReportTask_FullMethodName        = "/proto.SantaiziService/ReportTask"
	SantaiziService_RequestTask_FullMethodName       = "/proto.SantaiziService/RequestTask"
	SantaiziService_IOStream_FullMethodName          = "/proto.SantaiziService/IOStream"
	SantaiziService_LookupGeoIP_FullMethodName       = "/proto.SantaiziService/LookupGeoIP"
)

// SantaiziServiceClient is the client API for SantaiziService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SantaiziServiceClient interface {
	ReportSystemState(ctx context.Context, in *State, opts ...grpc.CallOption) (*Receipt, error)
	ReportSystemInfo(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Receipt, error)
	ReportTask(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Receipt, error)
	RequestTask(ctx context.Context, in *Host, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error)
	IOStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOStreamData, IOStreamData], error)
	LookupGeoIP(ctx context.Context, in *GeoIP, opts ...grpc.CallOption) (*GeoIP, error)
}

type santaiziServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSantaiziServiceClient(cc grpc.ClientConnInterface) SantaiziServiceClient {
	return &santaiziServiceClient{cc}
}

func (c *santaiziServiceClient) ReportSystemState(ctx context.Context, in *State, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, SantaiziService_ReportSystemState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *santaiziServiceClient) ReportSystemInfo(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, SantaiziService_ReportSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *santaiziServiceClient) ReportTask(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, SantaiziService_ReportTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *santaiziServiceClient) RequestTask(ctx context.Context, in *Host, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SantaiziService_ServiceDesc.Streams[0], SantaiziService_RequestTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Host, Task]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SantaiziService_RequestTaskClient = grpc.ServerStreamingClient[Task]

func (c *santaiziServiceClient) IOStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOStreamData, IOStreamData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SantaiziService_ServiceDesc.Streams[1], SantaiziService_IOStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IOStreamData, IOStreamData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SantaiziService_IOStreamClient = grpc.BidiStreamingClient[IOStreamData, IOStreamData]

func (c *santaiziServiceClient) LookupGeoIP(ctx context.Context, in *GeoIP, opts ...grpc.CallOption) (*GeoIP, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoIP)
	err := c.cc.Invoke(ctx, SantaiziService_LookupGeoIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SantaiziServiceServer is the server API for SantaiziService service.
// All implementations must embed UnimplementedSantaiziServiceServer
// for forward compatibility.
type SantaiziServiceServer interface {
	ReportSystemState(context.Context, *State) (*Receipt, error)
	ReportSystemInfo(context.Context, *Host) (*Receipt, error)
	ReportTask(context.Context, *TaskResult) (*Receipt, error)
	RequestTask(*Host, grpc.ServerStreamingServer[Task]) error
	IOStream(grpc.BidiStreamingServer[IOStreamData, IOStreamData]) error
	LookupGeoIP(context.Context, *GeoIP) (*GeoIP, error)
	mustEmbedUnimplementedSantaiziServiceServer()
}

// UnimplementedSantaiziServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSantaiziServiceServer struct{}

func (UnimplementedSantaiziServiceServer) ReportSystemState(context.Context, *State) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSystemState not implemented")
}
func (UnimplementedSantaiziServiceServer) ReportSystemInfo(context.Context, *Host) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSystemInfo not implemented")
}
func (UnimplementedSantaiziServiceServer) ReportTask(context.Context, *TaskResult) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTask not implemented")
}
func (UnimplementedSantaiziServiceServer) RequestTask(*Host, grpc.ServerStreamingServer[Task]) error {
	return status.Error(codes.Unimplemented, "method RequestTask not implemented")
}
func (UnimplementedSantaiziServiceServer) IOStream(grpc.BidiStreamingServer[IOStreamData, IOStreamData]) error {
	return status.Error(codes.Unimplemented, "method IOStream not implemented")
}
func (UnimplementedSantaiziServiceServer) LookupGeoIP(context.Context, *GeoIP) (*GeoIP, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupGeoIP not implemented")
}
func (UnimplementedSantaiziServiceServer) mustEmbedUnimplementedSantaiziServiceServer() {}
func (UnimplementedSantaiziServiceServer) testEmbeddedByValue()                         {}

// UnsafeSantaiziServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SantaiziServiceServer will
// result in compilation errors.
type UnsafeSantaiziServiceServer interface {
	mustEmbedUnimplementedSantaiziServiceServer()
}

func RegisterSantaiziServiceServer(s grpc.ServiceRegistrar, srv SantaiziServiceServer) {
	// If the following call panics, it indicates UnimplementedSantaiziServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SantaiziService_ServiceDesc, srv)
}

func _SantaiziService_ReportSystemState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SantaiziServiceServer).ReportSystemState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SantaiziService_ReportSystemState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SantaiziServiceServer).ReportSystemState(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _SantaiziService_ReportSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SantaiziServiceServer).ReportSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SantaiziService_ReportSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SantaiziServiceServer).ReportSystemInfo(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _SantaiziService_ReportTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SantaiziServiceServer).ReportTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SantaiziService_ReportTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SantaiziServiceServer).ReportTask(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _SantaiziService_RequestTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Host)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SantaiziServiceServer).RequestTask(m, &grpc.GenericServerStream[Host, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SantaiziService_RequestTaskServer = grpc.ServerStreamingServer[Task]

func _SantaiziService_IOStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SantaiziServiceServer).IOStream(&grpc.GenericServerStream[IOStreamData, IOStreamData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SantaiziService_IOStreamServer = grpc.BidiStreamingServer[IOStreamData, IOStreamData]

func _SantaiziService_LookupGeoIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoIP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SantaiziServiceServer).LookupGeoIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SantaiziService_LookupGeoIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SantaiziServiceServer).LookupGeoIP(ctx, req.(*GeoIP))
	}
	return interceptor(ctx, in, info, handler)
}

// SantaiziService_ServiceDesc is the grpc.ServiceDesc for SantaiziService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SantaiziService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SantaiziService",
	HandlerType: (*SantaiziServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSystemState",
			Handler:    _SantaiziService_ReportSystemState_Handler,
		},
		{
			MethodName: "ReportSystemInfo",
			Handler:    _SantaiziService_ReportSystemInfo_Handler,
		},
		{
			MethodName: "ReportTask",
			Handler:    _SantaiziService_ReportTask_Handler,
		},
		{
			MethodName: "LookupGeoIP",
			Handler:    _SantaiziService_LookupGeoIP_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestTask",
			Handler:       _SantaiziService_RequestTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IOStream",
			Handler:       _SantaiziService_IOStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/santaizi.proto",
}
