services:
  dashboard:
    image: santaizi_image_url
    restart: always
    volumes:
      - ./data:/var/lib/santaizi-dashboard
      - ./config/dashboard.yaml:/etc/santaizi/dashboard.yaml:ro
    ports:
      - santaizi_site_port:80
      - santaizi_grpc_port:santaizi_grpc_port
